import numpy
value_names = ('MV',)
version = 1
round_digits = 2
units = 'cm^3/mol'
components = {'solute': 1, 'solvent': 0}
molecule_format = 'dev.0.0.5'
model_type = 'MLRX'
intercept = False
fragmentlist = numpy.array([('[CH3D1R0]', '1 atom, general, table 1', 0.0),
                            ('[CH3D1R0;$(*OC(OC)(OC)C),$(*O[CH1](OC)OC),$(*OC(OC)(C)C),$(*O[CH1](OC)C)]', '1 atom, specific, table 1', 0.0),
                            ('[CH2D2R0]', '1 atom, general, table 1', 0.0),
                            ('[CH1D3R0]', '1 atom, general, table 1', 0.0),
                            ('[CH0D4R0]', '1 atom, general, table 1', 0.0),
                            ('[CH2D1R0$(*=*)]', '1 atom, general, table 1', 0.0),
                            ('[CH1D2R0$(*=*)]', '1 atom, general, table 1', 0.0),
                            ('[CH0D3R0$(*=*)]', '1 atom, general, table 1', 0.0),
                            ('[CH0D2R0$(*(=*)=*)]', '1 atom, general, table 1', 0.0),
                            ('[CH1D1R0$(*#*)]', '1 atom, general, table 1', 0.0),
                            ('[CH0D2R0$(*#*)]', '1 atom, general, table 1', 0.0),
                            ('[OH1D1R0]', '1 atom, general, table 1', 0.0),
                            ('[OH0D2R0]', '1 atom, general, table 1', 0.0),
                            ('[OH0R0$(*=N)]', '1 atom, specific, table 1', 0.0),
                            ('[CH0D3R0](=O)-[OH0]', '3 atom, general, table 1', 0.0),
                            ('[CH1D2R0]=O', '2 atom, general, table 1', 0.0),
                            ('[CH0D3R0](=O)-[OH1]', '3 atom, general, table 1', 0.0),
                            ('[CH0D3R0$(*(-[CR0])-[CR0])]=O', '2 atom, specific, table 1', 0.0),
                            ('[CH0D3R0$(*(-[C,O;R0])-[N,O;R0])]=O', '2 atom, specific, table 1', 0.0),
                            ('[CH0D3R0$(*(-[NR0])-[NR0])]=O', '2 atom, specific, table 1', 0.0),
                            ('[CH0D2RO$(*(=*)=*)]=O', '2 atom, general, table 1', 0.0),
                            ('[OH0R0]-[CH2D2R0]-[OH0R0]', '3 atom, general, table 1', 0.0),
                            ('[OH0R0]-[CH1D3R0]-[OH0R0]', '3 atom, general, table 1', 0.0),
                            ('[OH0R0]-[CH1D3R0](-[OH0R0])-[OH0R0]', '4 atom, general, table 1', 0.0),
                            ('[OH0R0]-[CH0D4R0](-[OH0R0])-[OH0R0]', '4 atom, general, table 1', 0.0),
                            ('[OH0R0]-[CH0D4R0](-[OH0R0])(-[OH0R0])-[OH0R0]', '5 atom, general, table 1', 0.0),
                            ('O=[CH0D3R0](-[OH0R0])-[OH0R0]', '3 atom, general, table 1', 0.0),
                            ('F-[CH0D4R0](-F)(-[OH0R0])-[OH0R0]', '5 atom, general, table 1', 0.0),
                            ('F-[NH0D3R0v3](-F)-[CH0D4R0](-[NH0D3R0v3](-F)-F)(-[OH0R0])-[OH0R0]', '9 atom, general, table 1', 0.0),
                            ('[NH2D1R0v3]', '1 atom, general, table 1', 0.0),
                            ('[NH2D1R0v3;$(*-[CR0]-[CR0]-N(=O)=O),$(*-[CR0]-[CR0]-[CH0D3R0](=O)-[OH1R0])]', '1 atom, specific, table 1', 0.0),
                            ('[NH1D2R0v3]', '1 atom, general, table 1', 0.0),
                            ('[NH0D3R0v3]', '1 atom, general, table 1', 0.0),
                            ('[NH0D2R0v3$(*(=*)-*)]', '1 atom, general, table 1', 0.0),
                            ('[CH0D3R0$(*(-[NR0])-[NR0])]=[NH1D1R0v3]', '2 atom, specific, table 1', 0.0),
                            ('[CH0D3R0$(*(-[CR0])-[CR0])]=[NH0D2R0v3]', '2 atom, specific, table 1', 0.0),
                            ('[CH0D3R0$(*(-[NR0])-[NR0])]=[NH0D2R0v3]', '2 atom, specific, table 1', 0.0),
                            ('[NH0D2R0v3]=[CH0D2R0]=[NH0D2R0v3]', '3 atom, general, table 1', 0.0),
                            ('[CH0D2R0]#[NH0D1R0v3]', '3 atom, general, table 1', 0.0),
                            ('[NH0D2R0v3]=[NH0D2R0v5]#[NH0D1R0v3]', '3 atom, general, table 1', 0.0),
                            ('[NH0D2R0v3]-[OH1R0]', '2 atom, general, table 1', 0.0),
                            ('[CH2D2R0]-[NH0D3R0v5](=O)=O', '4 atom, general, table 1', 0.0),
                            ('[CH1D3R0]-[NH0D3R0v5](=O)=O', '4 atom, general, table 1', 0.0),
                            ('[CH1D2R0$(*=*)]-[NH0D3R0v5](=O)=O', '4 atom, general, table 1', 0.0),
                            ('[CH0D4R0]-[NH0D3R0v5](=O)=O', '4 atom, general, table 1', 0.0),
                            ('[CH1D3R0](-[NH0D3R0v5](=O)=O)-[NH0D3R0v5](=O)=O', '7 atom, general, table 1', 0.0),
                            ('[CH0D4R0](-[NH0D3R0v5](=O)=O)-[NH0D3R0v5](=O)=O', '7 atom, general, table 1', 0.0),
                            ('[CH0D3R0$(*=*)](-[NH0D3R0v5](=O)=O)-[NH0D3R0v5](=O)=O', '7 atom, general, table 1', 0.0),
                            ('[CH0D4R0](-[NH0D3R0v5](=O)=O)(-[NH0D3R0v5](=O)=O)-[NH0D3R0v5](=O)=O', '10 atom, general, table 1', 0.0),
                            ('[CH2D2R0]-[OH0R0]-[NH0D3R0v5](=O)=O', '5 atom, general, table 1', 0.0),
                            ('[CH2D2R0]=[NH0D2R0v3]-[OH0R0]-[NH0D3R0v5](=O)=O', '6 atom, general, table 1', 0.0),
                            ('[CH0D4R0](-[CH2D2R0]-[OH0R0]-[NH0D3R0v5](=O)=O)-[CH2D2R0]-[OH0R0]-[NH0D3R0v5](=O)=O', '11 atom, general, table 1', 0.0),
                            ('[CH0D4R0](-[CH2D2R0]-[OH0R0]-[NH0D3R0v5](=O)=O)(-[CH2D2R0]-[OH0R0]-[NH0D3R0v5](=O)=O)-[CH2D2R0]-[OH0R0]-[NH0D3R0v5](=O)=O', '16 atom, general, table 1', 0.0),
                            ('[OH0R0]-[NH0D2R0v3]=O', '3 atom, general, table 1', 0.0),
                            ('[CH0D4R0](-[NH0D3R0v5](=O)=O)(-[NH0D3R0v5](=O)=O)-F', '8 atom, general, table 1', 0.0),
                            ('[CH0D4R0](-F)(-F)-[NH0D3R0v5](=O)=O', '6 atom, general, table 1', 0.0),
                            ('[OH0R0]-[CH0D4R0](-F)(-[NH0D3R0v5](=O)=O)-[NH0D3R0v5](=O)=O', '9 atom, general, table 1', 0.0),
                            ('[NH1D2R0v3]-[NH0D3R0v5](=O)=O', '4 atom, general, table 1', 0.0),
                            ('[NH0D3R0v3]-[NH0D3R0v5](=O)=O', '4 atom, general, table 1', 0.0),
                            ('[NH0D3R0v3](-[NH0D3R0v5](=O)=O)-[NH0D3R0v5](=O)=O', '7 atom, general, table 1', 0.0),
                            ('[CH0D3R0$(*(-[CR0])-[CR0])]=[NH0D2R0v3]-[NH0D3R0v5](=O)=O', '5 atom, specific, table 1', 0.0),
                            ('[CH0D4R0](-F)(-F)-F', '4 atom, general, table 1', 0.0),
                            ('[CH1D3R0](-F)-F', '3 atom, general, table 1', 0.0),
                            ('[CH0D4R0](-F)-F', '3 atom, general, table 1', 0.0),
                            ('[OH0R0]-[CH0D4R0](-F)(-F)-F', '5 atom, general, table 1', 0.0),
                            ('[NH0D3R0](-F)-F', '3 atom, general, table 1', 0.0),
                            ('F', '1 atom, general, table 1', 0.0),
                            ('Cl', '1 atom, general, table 1', 0.0),
                            ('[CH0D4R0](-Cl)(-Cl)-Cl', '4 atom, general, table 1', 0.0),
                            ('[CH0D3R0](=O)-Cl', '3 atom, general, table 1', 0.0),
                            ('Br', '1 atom, general, table 1', 0.0),
                            ('[SH0D2R0v2]', '1 atom, general, table 1', 0.0),
                            ('[SH1D1R0v2]', '1 atom, general, table 1', 0.0),
                            ('[SH0D1R0v2$(*=*)]', '1 atom, general, table 1', 0.0),
                            ('[CH0D3R0$(*(-[CR0])-[CR0])]=[SH0D1R0v2]', '2 atom, specific, table 1', 0.0),
                            ('[CH0D3R0$(*(-[NR0])-[NR0])]=[SH0D1R0v2]', '2 atom, specific, table 1', 0.0),
                            ('[SH0D4R0v6](=O)(=O)', '3 atom, general, table 1', 0.0),
                            ('[SH0D3R0v4](=O)(-[OH0R0])-[OH0R0]', '4 atom, general, table 1', 0.0),
                            ('[SH0D4R0v6](=O)(=O)(-[OH0R0])-[OH0R0]', '5 atom, general, table 1', 0.0),
                            ('I', '1 atom, general, table 1 (extrapolated)', 0.0),
                            ('[CH2D2R$(*(-[CR])-[CR])]', '1 atom, specific, table 3', 0.0),
                            ('[CH2D2R$(*(-[CR])-[NR])]', '1 atom, specific, table 3', 0.0),
                            ('[CH2D2R$(*(-[NR])-[NR])]', '1 atom, specific, table 3', 0.0),
                            ('[CH2D2R$(*(-[OR])-[CR])]', '1 atom, specific, table 3', 0.0),
                            ('[CH2D2R$(*(-[OR])-[NR])]', '1 atom, specific, table 3', 0.0),
                            ('[CH2D2R$(*(-[OR])-[OR])]', '1 atom, specific, table 3', 0.0),
                            ('[CH1D3R$(*(-[CR])(-[CR])-[CR])]', '1 atom, specific, table 3', 0.0),
                            ('[CH1D3R$(*(-[NR])(-[NR])-[CR])]', '1 atom, specific, table 3', 0.0),
                            ('[CH1D3R$(*(-[NR])(-[NR])-[NR])]', '1 atom, specific, table 3', 0.0),
                            ('[CH1D3R$(*(-[OR])(-[OR])-[CR])]', '1 atom, specific, table 3', 0.0),
                            ('[CH1D3R$(*(-[CR])(-[CR])-[NR])]', '1 atom, specific, table 3', 0.0),
                            ('[CH1D3R$(*(-[OR])(-[NR])-[CR])]', '1 atom, specific, table 3', 0.0),
                            ('[CH1D3R$(*(-[AR])-[AR])]', '1 atom, specific, table 3', 0.0),
                            ('[CH0D4R$(*(-[AR])-[AR]-[CR])]', '1 atom, specific, table 3', 0.0),
                            ('[CH1D2R$(*-[AR])]=[CH1D2R$(*-[AR])]', '2 atom, specific, table 3', 0.0),
                            ('[CH1D2R$(*-[AR])]=[CH0D3R;$(*(-[AR])-[AR]),$(*(-[AR])-[CR0])]', '2 atom, specific, table 3', 0.0),
                            ('[CH0D3R$(*(=*)(-[CR])-[CR])]', '1 atom, specific, table 3', 0.0),
                            ('[CH0D3R;$(*(-[AR])-[AR]),$(*(-[AR])-[CR0])]=[CH0D3R;$(*(-[AR])-[AR]),$(*(-[AR])-[CR0])]', '2 atom, specific, table 3', 0.0),
                            ('[CH0D3R;$(*1AAAA1),$(*1AAAAA1),$(*1AAAAAA1)]=[CH0D3R;$(*1AAAA1),$(*1AAAAA1),$(*1AAAAAA1)]', '2 atom, general, table 3', 0.0),
                            ('[CH0D4R;$(*1AAAA1),$(*1AAAAA1),$(*1AAAAAA1)]', '1 atom, general, table 3', 0.0),
                            ('[CH0D4R;$(*12(AAAA1)AAAA2),$(*12(AAAAA1)AAAA2),$(*12(AAAAAA1)AAAA2),$(*12(AAAAA1)AAAAA2),$(*12(AAAAAA1)AAAAA2),$(*12(AAAAAA1)AAAAAA2)]', '1 atom, general, table 3', 0.0),
                            ('[CH0D4R$(*(-c)-c);$(*1AAAA1),$(*1AAAAA1),$(*1AAAAAA1)]', '1 atom, specific, table 3', 0.0),
                            ('[CH1D3R$(*(-[CR])-[CR])]-[NH0D3R0v5](=O)=O', '4 atom, specific, table 3', 0.0),
                            ('[NH0D3R0v5$(*-[CR])](=O)=O', '3 atom, specific, table 3', 0.0),
                            ('[CH0D4R$(*(-[CR])(-[CR])-[CR])]-[NH0D3R0v5](=O)=O', '4 atom, specific, table 3', 0.0),
                            ('[CH0D4R$(*(-[CR])-[CR])](-[NH0D3R0v5](=O)=O)-[NH0D3R0v5](=O)=O', '7 atom, specific, table 3', 0.0),
                            ('[CH1D3R$(*(-[CR])-[CR])]-[OH0R0]-[NH0D3R0v5](=O)=O', '5 atom, specific, table 3', 0.0),
                            ('[CH0D4R$(*(-[CR])(-[CR])-[CR])]-[NH0D2R0v3]=O', '3 atom, specific, table 3', 0.0),
                            ('[NH0D3Rv3$(*(-[CR])-[CR])]-[NH0D3R0v5](=O)=O', '4 atom, specific, table 3', 0.0),
                            ('[NH1D2Rv3$(*-[CR])]-[NH0D3R0v5](=O)=O', '4 atom, specific, table 3', 0.0),
                            ('[NH0D3Rv3$(*(-[CR])-[CR])]-[NH0D2R0v3]=O', '3 atom, specific, table 3', 0.0),
                            ('[CH0D3R$(*(-[NR])-[NR])]=[NH0D2R0v3]-[NH0D2R0v3]=O', '5 atom, specific, table 3', 0.0),
                            ('[NH1D2Rv3$(*(-[CR])-[C,N;R])]', '1 atom, specific, table 3', 0.0),
                            ('[NH0D3Rv3$(*(-[CR])(-[CR])-[CR])]', '1 atom, specific, table 3', 0.0),
                            ('[NH0D3Rv3$(*(-[CR])-[CR])]', '1 atom, specific, table 3', 0.0),
                            ('[CH1D2R$(*-[AR])]=[NH0D2Rv3$(*-[AR])]', '2 atom, specific, table 3', 0.0),
                            ('[CH0D3R$(*(-[AR])-[A&R,C&R0])]=[NH0D2Rv3$(*-[AR])]', '2 atom, specific, table 3', 0.0),
                            ('[NH0D2Rv3$(*-[CR])]=[NH0D2Rv3$(*-[CR])]', '2 atom, specific, table 3', 0.0),
                            ('[CH0D3R$(*(-[CR])-[CR])]=[NH0D2R0v3]-[OH1R0]', '3 atom, specific, table 3', 0.0),
                            ('[OH0D2R$(*(-[CR])-[CR])]', '1 atom, specific, table 3', 0.0),
                            ('[OH0D2R$(*(-[CR])-[OR])]', '1 atom, specific, table 3', 0.0),
                            ('[CH0D3R$(*(-[CR])-[AR])]=O', '2 atom, specific, table 3', 0.0),
                            ('[CH0D3R$(*(-[OR])-[OR])]=O', '2 atom, specific, table 3', 0.0),
                            ('[CH0D3R$(*(-[NR])-[NR])]=O', '2 atom, specific, table 3', 0.0),
                            ('[CH0D4R$(*(-[CR])-[CR])](-[NH0D3R0v3](-F)F)-[NH0D3R0v3](-F)F', '7 atom, specific, table 3', 0.0),
                            ('[SH0D4Rv6$(*(-[AR])-[AR])](=O)=O', '3 atom, specific, table 3', 0.0),
                            ('[cR1]1[cR1][cR1][cR1][cR1][cR1]1', '6 atom, general, table 6', 0.0),
                            ('[nR1]1[cR1][cR1][cR1][cR1][cR1]1', '6 atom, general, table 6', 0.0),
                            ('[nR1]1[cR1][cR1][nR1][cR1][cR1]1', '6 atom, general, table 6', 0.0),
                            ('[nR1]1[nR1][cR1][cR1][cR1][cR1]1', '6 atom, general, table 6', 0.0),
                            ('[nR1]1[cR1][nR1][cR1][cR1][cR1]1', '6 atom, general, table 6', 0.0),
                            ('[nR1]1[cR1][nR1][cR1][nR1][cR1]1', '6 atom, general, table 6', 0.0),
                            ('[nR1]1[nR1][nR1][nR1][cR1][cR1]1', '6 atom, general, table 6', 0.0),
                            ('[nR1]1[nR1][cR1][nR1][nR1][cR1]1', '6 atom, general, table 6', 0.0),
                            ('[nR1]1[cR1][cR1][cR1][cR1]1', '5 atom, general, table 6', 0.0),
                            ('[nR1]1[nR1][cR1][cR1][cR1]1', '5 atom, general, table 6', 0.0),
                            ('[nR1]1[cR1][nR1][cR1][cR1]1', '5 atom, general, table 6', 0.0),
                            ('[nR1]1[nR1][nR1][cR1][cR1]1', '5 atom, general, table 6', 0.0),
                            ('[nR1]1[nR1][cR1][nR1][cR1]1', '5 atom, general, table 6', 0.0),
                            ('[nR1]1[nR1][nR1][nR1][cR1]1', '5 atom, general, table 6', 0.0),
                            ('[nR1]1[oR1][nR1][cR1][cR1]1', '5 atom, general, table 6', 0.0),
                            ('[nR1]1[oR1][nR1](-,=O)[cR1][cR1]1', '6 atom, general, table 6', 0.0),
                            ('[CH3D1$(*-[c,n])]', '1 atom, general, table 6', 0.0),
                            ('[CH2D2$(*-c)]', '1 atom, general, table 6', 0.0),
                            ('[CH2D2$(*-n)]', '1 atom, general, table 6', 0.0),
                            ('[CH2D2$(*(-c)-[c,A&R])]', '1 atom, specific, table 6', 0.0),  # put above previous 2
                            ('[CH1D3$(*-c)]', '1 atom, general, table 6', 0.0),
                            ('[CH0D4$(*-c)]', '1 atom, general, table 6', 0.0),
                            ('[CH1D2$(*(-[c,n])=*)]', '1 atom, general, table 6', 0.0),
                            ('[CH0D3$(*(-c)=*)]', '1 atom, general, table 6', 0.0),
                            ('[NH2D1R0v3$(*-c)]', '1 atom, general, table 6', 0.0),
                            ('[NH2D1R0v3;$(*-c:[aR1]-[NH0D3R0v5](=O)=O),$(*-c:[aR1]:[aR1]-[NH0D3R0v5](=O)=O),$(*-c:[aR1]:[aR1]:[aR1]-[NH0D3R0v5](=O)=O)]', '1 atom, specific, table 6', 0.0),
                            ('[NH1D1R0v3$(*=c)]', '1 atom, general, table 6', 0.0),
                            ('[NH1D1R0v3;$(*=c:[aR1]-[NH0D3R0v5](=O)=O),$(*=c:[aR1]:[aR1]-[NH0D3R0v5](=O)=O),$(*=c:[aR1]:[aR1]:[aR1]-[NH0D3R0v5](=O)=O)]', '1 atom, specific, table 6', 0.0),
                            ('[NH1D2v3$(*-c)]', '1 atom, general, table 6', 0.0),
                            ('[NH1D2v3$(*-c)]-[NH2D1R0v3]', '2 atom, general, table 6', 0.0),
                            ('[CH0D3$(*(-c)-c)]=[NH1D1R0v3]', '2 atom, general, table 6', 0.0),
                            ('[NH0D2R0v3$(*-c)]=[NH0D2R0v5]#[NH0D1R0v3]', '3 atom, general, table 6', 0.0),
                            ('[NH0D3v3$(*(-c)(-C)-[C,N])]', '1 atom, general, table 6', 0.0),
                            ('[NH0D3v3$(*(-c)(-c)-[C,c])]', '1 atom, general, table 6', 0.0),
                            ('[NH0D3R0v3$(*-c)](-F)-F', '3 atom, general, table 6', 0.0),
                            ('[CH1D3R0$(*-c)](-[NH0D3R0v3](-F)-F)-[NH0D3R0v3](-F)-F', '7 atom, general, table 6', 0.0),
                            ('[NH1D2v3$(*(-c)-c)]', '1 atom, general, table 6', 0.0),
                            ('[NH1D2v3$(*-c)]-[NH1D2v3$(*-c)]', '2 atom, general, table 6', 0.0),
                            ('[NH0D2Rv3$(*-c)]=[NH0D2Rv3$(*-c)]', '2 atom, general, table 6', 0.0),
                            ('[NH0D2R0v3$(*-c)]=[NH0D2R0v3$(*-c)]', '2 atom, general, table 6', 0.0),
                            ('[NH0D2v3$(*-n)]=[NH0D2v3$(*-n)]', '2 atom, general, table 6', 0.0),
                            ('[NH0D2Rv3$(*(=c)-c)]', '1 atom, general, table 6', 0.0),
                            ('[NH0D2Rv3$(*-c)]=[NH0D3Rv5$(*(-c)=O)]', '3 atom, general, table 6', 0.0),
                            ('[CH0D2$(*-c)]#[NH0D1v3]', '2 atom, general, table 6', 0.0),
                            ('[NH0D3R0v5$(*-[c,n])](=O)=O', '3 atom, general, table 6', 0.0),
                            ('[NH0D2R0v3$(*-c)]=O', '2 atom, general, table 6', 0.0),
                            ('[CH1D3$(*-[c,n])](-[NH0D3R0v5](=O)=O)-[NH0D3R0v5](=O)=O', '7 atom, general, table 6', 0.0),
                            ('[CH0D4$(*-[c,n])](-[NH0D3R0v5](=O)=O)(-[NH0D3R0v5](=O)=O)-[NH0D3R0v5](=O)=O', '10 atom, general, table 6', 0.0),
                            ('[CH0D4$(*-[c,n])](-[NH0D3R0v5](=O)=O)-[NH0D3R0v5](=O)=O', '7 atom, general, table 6', 0.0),
                            ('[CH0D4$(*-[c,n])](-F)(-[NH0D3R0v5](=O)=O)-[NH0D3R0v5](=O)=O', '8 atom, general, table 6', 0.0),
                            ('[CH0D4$(*-c)](-Cl)(-[NH0D3R0v5](=O)=O)-[NH0D3R0v5](=O)=O', '8 atom, general, table 6', 0.0),
                            ('[CH0D4$(*-n)](-[NH0D3R0v3](-F)-F)(-[NH0D3R0v5](=O)=O)-[NH0D3R0v5](=O)=O', '10 atom, general, table 6', 0.0),
                            ('[CH2D2;$(*-c:[a!#6]),$(*-c:a:[a!#6]),$(*-c:a:a:[a!#6]),$(*-c:a:a:a:[a!#6])]-[OH0D2R0]-[NH0D3R0v5](=O)=O', '5 atom, general, table 6', 0.0),
                            ('[CH2D2$(*-n)]-[OH0D2R0]-[NH0D3R0v5](=O)=O', '5 atom, general, table 6', 0.0),
                            ('[NH1D2R0v3$(*-c)]-[NH0D3R0v5](=O)=O', '4 atom, general, table 6', 0.0),
                            ('[NH0D3v3!$(*-c:[a!#6])!$(*-c:a:[a!#6])!$(*-c:a:a:[a!#6])!$(*-c:a:a:a:[a!#6])]-[NH0D3R0v5](=O)=O', '4 atom, general, table 6', 0.0),
                            ('[NH0D3v3;$(*-c:[a!#6]),$(*-c:a:[a!#6]),$(*-c:a:a:[a!#6]),$(*-c:a:a:a:[a!#6])]-[NH0D3R0v5](=O)=O', '4 atom, general, table 6', 0.0),
                            ('[NH0D3R0v5$(*-c)](=O)=[NH0D2R0v3$(*-c)]-[NH0D3R0v5](=O)=O', '6 atom, general, table 6', 0.0),
                            ('[OH1D1R0$(*-c)]', '1 atom, general, table 6', 0.0),
                            ('[OH0D2R0$(*-c)]', '1 atom, general, table 6', 0.0),
                            ('[OH0D2R0$(*-c)]-[CH3D1]', '1 atom, general, table 6', 0.0),
                            ('[CH0D3$(*-c)]=O', '2 atom, general, table 6', 0.0),
                            ('[CH0D3$(*-c)](=O)-[OH1D1]', '3 atom, general, table 6', 0.0),
                            ('[CH0D3$(*-c)](=O)-[OH0D2]', '3 atom, general, table 6', 0.0),
                            ('[CH1D2$(*-c)]=O', '2 atom, general, table 6', 0.0),
                            ('[OH0D1R0$(*=n)]', '1 atom, general, table 6', 0.0),
                            ('[OH0D2R0$(*(-c)-c)]', '1 atom, specific, table 6', 0.0),
                            ('[CH0D3$(*(-c)-c)]=O', '2 atom, specific, table 6', 0.0),
                            ('[FH0D1$(*-c)]', '1 atom, general, table 6', 0.0),
                            ('[FH0D1$(*-n)]', '1 atom, general, table 6', 0.0),
                            ('[ClH0D1$(*-c)]', '1 atom, general, table 6', 0.0),
                            ('[ClH0D1$(*-n)]', '1 atom, general, table 6', 0.0),
                            ('[BrH0D1$(*-c)]', '1 atom, general, table 6', 0.0),
                            ('[IH0D1$(*-c)]', '1 atom, general, table 6', 0.0),
                            ('[CH0D4$(*-c)](-F)(-F)-F', '4 atom, general, table 6', 0.0),
                            ('[SH0D2R0v2$(*(-c)-c)]', '1 atom, general, table 6', 0.0),
                            ('[cR1]', '1 atom, general, table 8', 0.0),
                            ('[nH0R1]', '1 atom, general, table 8', 0.0),
                            ('[nR1;H1D2,H0D3]', '1 atom, general, table 8', 0.0),
                            ('[cH0D3R1]=O', '1 atom, general, table 8', 0.0),
                            ('[oH0D2R1$(*(:c):[c,n])]', '1 atom, general, table 8', 0.0),
                            ('[oH0D2R1$(*(:n):n)]', '1 atom, general, table 8', 0.0),
                            ('[sH0D2R1v2]', '1 atom, general, table 8', 0.0),
                            ('[cR1;$(*:[a!R1]),$(*:a:[a!R1]),$(*:a:a:[a!R1]),$(*:a:a:a:[a!R1])]', '1 atom, general, table 9', 0.0),
                            ('[c!R1]', '1 atom, general, table 9', 0.0),
                            ('[n!R1]', '1 atom, general, table 9', 0.0),
                            ('[nH0R1$(*(:[c,o]):c);$(*:[a!R1]),$(*:a:[a!R1]),$(*:a:a:[a!R1]),$(*:a:a:a:[a!R1])]', '1 atom, general, table 9', 0.0),
                            ('[nH0R1$(*(:c):n);$(*:[a!R1]),$(*:a:[a!R1]),$(*:a:a:[a!R1]),$(*:a:a:a:[a!R1])]', '1 atom, general, table 9', 0.0),
                            ('[nH0R1$(*(:n):n);$(*:[a!R1]),$(*:a:[a!R1]),$(*:a:a:[a!R1]),$(*:a:a:a:[a!R1])]', '1 atom, general, table 9', 0.0),
                            ('[nR1;H1D2,H0D3;$(*(:c):c);$(*:[a!R1]),$(*:a:[a!R1]),$(*:a:a:[a!R1]),$(*:a:a:a:[a!R1])]', '1 atom, general, table 9', 0.0),
                            ('[nR1;H1D2,H0D3;$(*(:[c,n]):c);$(*:[a!R1]),$(*:a:[a!R1]),$(*:a:a:[a!R1]),$(*:a:a:a:[a!R1])]', '1 atom, general, table 9', 0.0),
                            ('[oH0D2R1$(*(:c):[c,n]);$(*:[a!R1]),$(*:a:[a!R1]),$(*:a:a:[a!R1]),$(*:a:a:a:[a!R1])]', '1 atom, general, table 9', 0.0),
                            ('[oH0D2R1$(*(:c):c);$(*:[a!R1]),$(*:a:[a!R1]),$(*:a:a:[a!R1]),$(*:a:a:a:[a!R1])]', '1 atom, general, table 9', 0.0),
                            ('[cH0D3R1;$(*:[a!R1]),$(*:a:[a!R1]),$(*:a:a:[a!R1]),$(*:a:a:a:[a!R1])]=O', '2 atom, general, table 9', 0.0),
                            ('[sH0D2R1v2;$(*:[a!R1]),$(*:a:[a!R1]),$(*:a:a:[a!R1]),$(*:a:a:a:[a!R1])]', '1 atom, general, table 9', 0.0),
                            ('[sH0D4R1v6;$(*:[a!R1]),$(*:a:[a!R1]),$(*:a:a:[a!R1]),$(*:a:a:a:[a!R1])](=O)=O', '3 atom, general, table 9', 0.0),
                            ], dtype=[('smarts', 'S150'), ('description', 'S30'), ('fragstdev', float)])
smiles_flag = 'neutrals'
domain = False
coefficientarrays = numpy.array([(28.52,),
                                 (24.69,),
                                 (14.77,),
                                 (1.76,),
                                 (-8.92,),
                                 (25.93,),
                                 (13.05,),
                                 (-2.85,),
                                 (6.32,),
                                 (23.02,),
                                 (7.92,),
                                 (11.77,),
                                 (4.19,),
                                 (5.87,),
                                 (21.83,),
                                 (22.47,),
                                 (23.35,),
                                 (9.71,),
                                 (12.83,),
                                 (14.89,),
                                 (22.95,),
                                 (38.35,),
                                 (23.03,),
                                 (34.61,),
                                 (18.74,),
                                 (37.27,),
                                 (24.38,),
                                 (46.45,),
                                 (82.61,),
                                 (15.52,),
                                 (11.96,),
                                 (6.03,),
                                 (-2.25,),
                                 (7.03,),
                                 (15.75,),
                                 (3.64,),
                                 (9.62,),
                                 (17.63,),
                                 (21.00,),
                                 (29.87,),
                                 (15.28,),
                                 (40.47,),
                                 (24.72,),
                                 (36.05,),
                                 (18.64,),
                                 (53.28,),
                                 (41.69,),
                                 (50.17,),
                                 (75.40,),
                                 (46.77,),
                                 (39.24,),
                                 (104.80,),
                                 (145.64,),
                                 (22.57,),
                                 (63.85,),
                                 (59.71,),
                                 (72.02,),
                                 (30.44,),
                                 (17.69,),
                                 (50.58,),
                                 (36.24,),
                                 (46.37,),
                                 (37.22,),
                                 (21.75,),
                                 (52.81,),
                                 (30.02,),
                                 (15.49,),
                                 (21.14,),
                                 (67.01,),
                                 (36.59,),
                                 (25.02,),
                                 (12.99,),
                                 (24.46,),
                                 (17.21,),
                                 (13.82,),
                                 (19.80,),
                                 (27.52,),
                                 (33.64,),
                                 (36.09,),
                                 (28.02,),
                                 (16.60,),
                                 (17.00,),
                                 (19.92,),
                                 (17.30,),
                                 (17.77,),
                                 (19.09,),
                                 (5.47,),
                                 (14.34,),
                                 (17.06,),
                                 (10.28,),
                                 (10.01,),
                                 (12.76,),
                                 (5.38,),
                                 (-5.63,),
                                 (27.89,),
                                 (13.98,),
                                 (-2.92,),
                                 (-1.75,),
                                 (26.50,),
                                 (-8.90,),
                                 (-5.52,),
                                 (26.61,),
                                 (28.40,),
                                 (25.64,),
                                 (23.25,),
                                 (44.47,),
                                 (38.27,),
                                 (11.57,),
                                 (21.22,),
                                 (31.05,),
                                 (15.30,),
                                 (40.18,),
                                 (7.26,),
                                 (-3.92,),
                                 (-2.61,),
                                 (20.48,),
                                 (10.54,),
                                 (24.82,),
                                 (18.37,),
                                 (5.05,),
                                 (6.52,),
                                 (12.41,),
                                 (16.69,),
                                 (13.34,),
                                 (62.13,),
                                 (25.36,),
                                 (23.52,),
                                 (28.06,),
                                 (32.39,),
                                 (33.68,),
                                 (34.80,),
                                 (35.30,),
                                 (37.81,),
                                 (36.94,),
                                 (21.97,),
                                 (22.79,),
                                 (25.79,),
                                 (28.31,),
                                 (28.68,),
                                 (32.29,),
                                 (33.94,),
                                 (39.78,),
                                 (22.04,),
                                 (10.19,),
                                 (16.72,),
                                 (16.20,),
                                 (-0.70,),
                                 (-16.03,),
                                 (12.60,),
                                 (-6.56,),
                                 (14.96,),
                                 (11.74,),
                                 (14.96,),
                                 (11.74,),
                                 (3.83,),
                                 (24.50,),
                                 (20.47,),
                                 (30.78,),
                                 (-7.73,),
                                 (2.14,),
                                 (29.64,),
                                 (65.40,),
                                 (16.74,),
                                 (28.49,),
                                 (13.87,),
                                 (23.01,),
                                 (28.71,),
                                 (8.67,),
                                 (27.13,),
                                 (25.27,),
                                 (25.78,),
                                 (10.96,),
                                 (56.72,),
                                 (80.17,),
                                 (45.56,),
                                 (62.55,),
                                 (71.33,),
                                 (83.04,),
                                 (48.11,),
                                 (43.39,),
                                 (27.69,),
                                 (19.62,),
                                 (27.67,),
                                 (49.27,),
                                 (12.49,),
                                 (4.82,),
                                 (26.99,),
                                 (11.08,),
                                 (25.80,),
                                 (15.74,),
                                 (21.31,),
                                 (5.41,),
                                 (8.46,),
                                 (32.24,),
                                 (13.13,),
                                 (9.99,),
                                 (22.12,),
                                 (19.93,),
                                 (26.53,),
                                 (28.17,),
                                 (38.00,),
                                 (31.72,),
                                 (3.92,),
                                 (7.89,),
                                 (5.27,),
                                 (14.10,),
                                 (9.24,),
                                 (10.54,),
                                 (21.30,),
                                 (4.00,),
                                 (6.86,),
                                 (5.38,),
                                 (6.40,),
                                 (7.64,),
                                 (9.89,),
                                 (1.24,),
                                 (6.42,),
                                 (10.00,),
                                 (11.50,),
                                 (13.83,),
                                 (15.96,),
                                 (27.22,),
                                 ], dtype=float)


def post_processing(prediction, error):
    local_prediction = round(prediction, round_digits)
    local_error = round(error, round_digits)
    return local_prediction, local_error


# python -m ifsqsar -s Nc1nc(nn1c1ncnc(c1N(=O)=O)n1nc(nc1N)N(=O)=O)N(=O)=O -f columns -q MV
